### ISSUE TITLE
Inclusion into HaxeFoundation/format

### ISSUE THREAD

**Issue by Speedphoenix** [RealyUniqueName/sourcemap#3]
We have a need for sourcemap on heaps, and realized it would make sense and would be more convenient if it were directly in format (https://github.com/HaxeFoundation/format)

Would it be ok if I added sourcemap to format, adapting it to the reader/writer pattern like the rest of format?

**Comment by RealyUniqueName** [comment]
I need it as a separate library.
However, feel free to copy.
